#MOVIE COLLECTION REQUESTS ----------------------------------------

GET https://cse341-teamproject-txpy.onrender.com/movies/
# Get All Movies in the collection

###

GET https://cse341-teamproject-txpy.onrender.com/movies/664c1ac58e6b8788e2d588e1
# Get a single movie

###

POST https://cse341-teamproject-txpy.onrender.com/movies HTTP/1.1
Content-Type: application/json

{
    "movieId": "a1b2c3c7",
    "title": "Inception 2",
    "director": "Christopher Nolan",
    "genre": "Sci-Fi",
    "releaseYear": 2010,
    "rating": "PG-13",
    "youtubeTrailer": "https://www.youtube.com/watch?v=YoHD9XEInc0",
    "reviewRating": 5,
    "duration": "148 minutes",
    "language": "English"
}

###

# PUT or Update Movies by ID
PUT https://cse341-teamproject-txpy.onrender.com/movies/664c1ac58e6b8788e2d588e0 HTTP/1.1
Content-Type: application/json

{
    "movieId": "a1b2c3c7",
    "title": "Inception 3",
    "director": "Christopher Nolan",
    "genre": "Sci-Fi",
    "releaseYear": 2010,
    "rating": "PG-13",
    "youtubeTrailer": "https://www.youtube.com/watch?v=YoHD9XEInc0",
    "reviewRating": 5,
    "duration": "148 minutes",
    "language": "English"
}

###

# DELETE Movies by ID
DELETE https://cse341-teamproject-txpy.onrender.com/movies/663d30df6a910b7d1e111a63 HTTP/1.1

#SHOW COLLECTION REQUESTS ----------------------------------------

###

# GET All Shows:
GET https://cse341-teamproject-txpy.onrender.com/shows

###

# GET Show By ID:
GET https://cse341-teamproject-txpy.onrender.com/shows/6652871df7447d017e4dfaf6



# ACCOUNTS COLLECTION REQUESTS ----------------------------------------

###

# GET All Accounts:
GET https://cse341-teamproject-txpy.onrender.com/accounts

###

# GET Account By ID:
GET https://cse341-teamproject-txpy.onrender.com/accounts/



# WATCH-LISTS COLLECTION REQUESTS ----------------------------------------

###

# GET All Watch-Lists:
GET https://cse341-teamproject-txpy.onrender.com/watch-list

###

# GET Watch-List By ID:
GET https://cse341-teamproject-txpy.onrender.com/watch-list/664c0876818e0fe059fa1d9b